### ISSUE TITLE
Getting TypeError with pandas_dq

### ISSUE THREAD

**Issue by SujeetO** [AutoViML/pandas_dq#4]
```
import pandas_dq as dq
import seaborn as sns

t = sns.load_dataset("tips")

dq.dq_report(t , verbose=1)
```
getting below error:
TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one.

using below versions:
numpy     : 1.22.4
pandas    : 1.5.3
**pandas_dq : 1.22**
matplotlib: 3.7.1
plotly    : 5.6.0
polars    : 0.17.3
spacy     : 3.5.3
pygwalker : 0.1.9
seaborn   : 0.11.2

**Comment by AutoViML** [comment]
Hi @SujeetO 
Thanks for pointing out the error 👍 

It has been fixed. Please upgrade to the latest version by 
`pip install pandas-dq --upgrade --ignore-installed`

Thanks
Auto Vimal

**Comment by SujeetO** [comment]
still not working. getting same error. i am using 1.27 version. 
numpy     : 1.24.3
pandas    : 1.5.3
**pandas_dq : 1.27**
matplotlib: 3.7.1
plotly    : 5.6.0
polars    : 0.17.3
spacy     : 3.5.3
pygwalker : 0.1.9
seaborn   : 0.11.2

**Comment by AutoViML** [comment]
Try this. You must have some old version hanging in there:
```
pip install pandas-dq==1.28 
```

I have tested the same on my machine and it works.
Auto Vimal

**Comment by SujeetO** [comment]
I am not sure, but getting this new error now:
ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed).

**Comment by AutoViML** [comment]
This seems to be your local machine setup issue. You need to try to Google search for such an error. I am sorry I can't help further.It works in a clean install on Colab and Kaggle kernels.Auto Vimal

    On Sunday, June 4, 2023 at 11:59:48 PM EDT, SujeetO ***@***.***> wrote:  
 
 


I am not sure, but getting this new error now:
ImportError: Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed).

**Comment by AutoViML** [comment]
You can re-open this if you still have an error @SujeetO
